let level='easy',queue=[],current=null,currentFactIndex=null,streak=0,round=0,answered=false;
let best=Number(localStorage.getItem('wg-best')||0);const BASE={x:0,y:0,w:1200,h:600},MIN_W=30,MIN_H=15;let view={...BASE};let lang=localStorage.getItem('wg-lang')||'en';const $=s=>document.querySelector(s),svg=$('#map'),markers=$('#markers');
countries.forEach(c=>{c.capital=CAPITALS[c.iso];c.facts=[{en:c.fact_en,fr:c.fact_fr,emoji:c.fact_emoji||'🤯',category:'geography'},...(EXTRA_FACTS[c.iso]||[])];delete c.fact_en;delete c.fact_fr;delete c.fact_emoji});
const T={en:{subtitle:'Find the country. Learn something surprising. Share it.',title:'Where is this country?',choose:'Choose a difficulty.',easy:'Easy',medium:'Medium',hard:'Hard',streak:'streak',record:'record',find:'Find',drag:'Drag • Pinch to zoom • Tap a country',distance:'Distance',next:'Next country',great:'Nice one!',miss:'Not this time!',almost:'So close!',near:'Very close!',notFar:'Not far!',capital:'Capital',share:'↗ Share this fact',copied:'✓ Copied!',shareText:'{country}\n{fact}\n\n🌍 GeoFact\n{url}'},fr:{subtitle:'Trouve le pays. Apprends un truc surprenant. Partage-le.',title:'Où se trouve ce pays ?',choose:'Choisis une difficulté.',easy:'Facile',medium:'Moyen',hard:'Difficile',streak:'série',record:'record',find:'Trouve',drag:'Déplace • Pince pour zoomer • Touche un pays',distance:'Distance',next:'Pays suivant',great:'Bien joué !',miss:'Pas cette fois !',almost:'Prrrresque !',near:'Tout près !',notFar:'Pas loin !',capital:'Capitale',share:'↗ Partager ce fact',copied:'✓ Copié !',shareText:'{country}\n{fact}\n\n🌍 GeoFact\n{url}'}};
function t(k){return T[lang][k]||k}function countryName(c){return lang==='fr'?c.nameFr||c.name:c.name}function currentFact(){return current&&currentFactIndex!==null?current.facts[currentFactIndex]:null}
function applyLang(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));$('#lang').value=lang;localStorage.setItem('wg-lang',lang);if(current){$('#countryName').textContent=countryName(current);if(answered)renderResult()}}
function selectFact(c){let memory={};try{memory=JSON.parse(localStorage.getItem('wg-seen-facts')||'{}')}catch{}let state=memory[c.iso]||{seen:[],last:null},available=c.facts.map((_,i)=>i).filter(i=>!state.seen.includes(i));if(!available.length){available=c.facts.map((_,i)=>i);if(available.length>1)available=available.filter(i=>i!==state.last);state.seen=[]}const index=available[Math.floor(Math.random()*available.length)];state.seen.push(index);state.last=index;memory[c.iso]=state;localStorage.setItem('wg-seen-facts',JSON.stringify(memory));return index}
function renderResult(){const fact=currentFact(),flag=current.a2.toUpperCase().replace(/./g,ch=>String.fromCodePoint(127397+ch.charCodeAt(0)));$('#resultFlag').textContent=flag;$('#resultCountry').textContent=countryName(current);$('#resultTitle').textContent=t('great');$('#capital').textContent=`${t('capital')} : ${current.capital[lang]}`;$('#fact').textContent=`${fact.emoji} ${fact[lang]}`;$('#share').textContent=t('share')}
function startGame(l){level=l;queue=shuffle(countries.filter(c=>difficulty(c)===l));streak=round=0;answered=false;$('#best').textContent=best;$('#start').classList.add('hidden');$('#game').classList.remove('hidden');nextRound()}
function difficulty(c){if(['AND','ATG','BHR','BRB','BRN','CPV','COM','DMA','GRD','KIR','LIE','MDV','MLT','MHL','MCO','NRU','PLW','KNA','LCA','VCT','WSM','SMR','STP','SYC','SGP','TON','TUV','VAT'].includes(c.iso))return'hard';if(['AFG','ALB','ARM','AZE','BWA','BIH','BOL','BTN','BGR','BFA','BDI','CMR','CAF','TCD','DJI','ERI','ETH','GAB','GEO','GNB','GUY','HND','KGZ','LAO','LBN','LSO','LBR','LBY','MDA','MRT','MWI','MNG','NAM','NPL','NER','NIC','OMN','PRY','RWA','SLE','SVN','TJK','TGO','TLS','TKM','UGA','UZB','VUT','ZMB'].includes(c.iso))return'medium';return'easy'}
function nextRound(){if(!queue.length)queue=shuffle(countries.filter(c=>difficulty(c)===level));current=queue.pop();currentFactIndex=null;round++;answered=false;$('#roundLabel').textContent=lang==='fr'?`Pays #${round}`:`Country #${round}`;$('#countryName').textContent=countryName(current);$('#result').classList.add('hidden');$('#distanceRow').classList.add('hidden');clearMarkers();resetView()}
function guessFromCountry(el,x,y){if(answered||!current)return;guess(90-y/600*180,x/1200*360-180,el.dataset.iso,x,y)}function guessFromPoint(x,y){if(answered||!current)return;guess(90-y/600*180,x/1200*360-180,null,x,y)}
function nearestBoundaryDistanceKm(lat,lon,c){const path=svg.querySelector(`.country-shape[data-iso="${c.iso}"]`);if(!path)return distanceKm(lat,lon,c.lat,c.lon);const total=path.getTotalLength();let best=Infinity;for(let d=0,step=Math.max(2,Math.min(8,total/220));d<=total;d+=step){const p=path.getPointAtLength(d);best=Math.min(best,distanceKm(lat,lon,90-p.y/600*180,p.x/1200*360-180))}return best}
function missMessage(d){return d<=75?t('almost'):d<=200?t('near'):d<=500?t('notFar'):t('miss')}
function guess(lat,lon,iso,gx,gy){if(answered)return;const dist=iso===current.iso?0:nearestBoundaryDistanceKm(lat,lon,current),threshold=level==='easy'?1000:level==='medium'?500:250,success=iso===current.iso||(!iso&&dist<=threshold),target=project(current.lon,current.lat),gp=gx==null?project(lon,lat):[gx,gy];if(success){answered=true;streak++;best=Math.max(best,streak);localStorage.setItem('wg-best',best);currentFactIndex=selectFact(current);clearMarkers();$('#distanceRow').classList.add('hidden');renderResult();$('#result').classList.remove('hidden')}else{streak=0;drawMarkers(gp,target);$('#distanceRow').classList.remove('hidden');const amount=dist<1?(lang==='fr'?'À quelques mètres !':'A few metres!'):`${Math.round(dist).toLocaleString(lang==='fr'?'fr-FR':'en-US')} km`;$('#distance').textContent=`${missMessage(dist)} · ${amount}`;$('#result').classList.add('hidden')}$('#streak').textContent=streak;$('#best').textContent=best}
function drawMarkers(g,tg){markers.innerHTML=`<line class="answer-line" x1="${g[0]}" y1="${g[1]}" x2="${tg[0]}" y2="${tg[1]}"/><circle class="guess-dot" cx="${g[0]}" cy="${g[1]}" r="7"/><circle class="answer-dot" cx="${tg[0]}" cy="${tg[1]}" r="7"/>`}function project(lon,lat){return[(lon+180)/360*1200,(90-lat)/180*600]}function distanceKm(a,b,c,d){const R=6371,r=Math.PI/180,x=Math.sin((c-a)*r/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin((d-b)*r/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function clearMarkers(){markers.innerHTML=''}function applyView(){svg.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`)}function resetView(){view={...BASE};applyView()}
function clampView(){view.w=Math.min(BASE.w,Math.max(MIN_W,view.w));view.h=Math.min(BASE.h,Math.max(MIN_H,view.h));view.x=Math.max(0,Math.min(BASE.w-view.w,view.x));view.y=Math.max(0,Math.min(BASE.h-view.h,view.y))}function zoomAt(f,cx=view.x+view.w/2,cy=view.y+view.h/2){view.x=cx-(cx-view.x)/f;view.y=cy-(cy-view.y)/f;view.w/=f;view.h/=f;clampView();applyView()}function clientToMap(x,y){const r=svg.getBoundingClientRect();return[(x-r.left)/r.width*view.w+view.x,(y-r.top)/r.height*view.h+view.y]}
const pointers=new Map();let gesture={suppressTap:false};
svg.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,target:e.target});svg.setPointerCapture(e.pointerId);if(pointers.size===1)gesture={moved:false,pinched:false,suppressTap:gesture.suppressTap,start:{x:e.clientX,y:e.clientY,target:e.target},startView:{...view}};else if(pointers.size===2){const[a,b]=[...pointers.values()];gesture.pinched=gesture.suppressTap=true;gesture.startView={...view};gesture.startDistance=Math.hypot(a.x-b.x,a.y-b.y);const mx=(a.x+b.x)/2,my=(a.y+b.y)/2;gesture.anchor=clientToMap(mx,my)}});
svg.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{...pointers.get(e.pointerId),x:e.clientX,y:e.clientY});const r=svg.getBoundingClientRect();if(pointers.size===1&&!gesture.pinched){const p=[...pointers.values()][0],dx=p.x-gesture.start.x,dy=p.y-gesture.start.y;if(Math.hypot(dx,dy)>8)gesture.moved=true;view.x=gesture.startView.x-dx/r.width*gesture.startView.w;view.y=gesture.startView.y-dy/r.height*gesture.startView.h}else if(pointers.size>=2){const[a,b]=[...pointers.values()],f=Math.hypot(a.x-b.x,a.y-b.y)/gesture.startDistance,mx=(a.x+b.x)/2,my=(a.y+b.y)/2;view.w=gesture.startView.w/f;view.h=gesture.startView.h/f;view.x=gesture.anchor[0]-(mx-r.left)/r.width*view.w;view.y=gesture.anchor[1]-(my-r.top)/r.height*view.h}clampView();applyView()});
function endPointer(e,cancelled=false){if(!pointers.has(e.pointerId))return;const ended=pointers.get(e.pointerId),canTap=!cancelled&&pointers.size===1&&!gesture.moved&&!gesture.pinched&&!gesture.suppressTap;pointers.delete(e.pointerId);if(pointers.size===1){const p=[...pointers.values()][0];gesture.start={x:p.x,y:p.y,target:p.target};gesture.startView={...view};gesture.moved=false;gesture.pinched=gesture.suppressTap=true}else if(!pointers.size){if(canTap){const[x,y]=clientToMap(e.clientX,e.clientY),country=ended.target.closest('.country-shape');country?guessFromCountry(country,x,y):guessFromPoint(x,y)}gesture.suppressTap=false}}svg.addEventListener('pointerup',e=>endPointer(e));svg.addEventListener('pointercancel',e=>endPointer(e,true));
$('#zoomIn').addEventListener('click',()=>zoomAt(1.5));$('#zoomOut').addEventListener('click',()=>zoomAt(1/1.5));$('#resetZoom').addEventListener('click',resetView);document.querySelectorAll('.levels button').forEach(b=>b.addEventListener('click',()=>startGame(b.dataset.level)));$('#next').addEventListener('click',nextRound);$('#lang').addEventListener('change',e=>{lang=e.target.value;applyLang()});$('#share').addEventListener('click',async()=>{const fact=currentFact(),url=location.href.split('#')[0],text=t('shareText').replace('{country}',countryName(current)).replace('{fact}',fact[lang]).replace('{url}',url);try{if(navigator.share)await navigator.share({title:'GeoFact',text,url});else{await navigator.clipboard.writeText(text);$('#share').textContent=t('copied');setTimeout(()=>$('#share').textContent=t('share'),1400)}}catch(e){if(e.name!=='AbortError')try{await navigator.clipboard.writeText(text)}catch{}}});applyLang();
